### ISSUE TITLE
Crash when saving a single frame

### ISSUE THREAD

**Issue by markmac99** [CroatianMeteorNetwork/cmn_binviewer#68]
On a linux machine, I get the following when I try to save a single 
frame from the "frames" view of a FITS file:

2023/09/19 09:59:26-INFO: Program start
2023/09/19 09:59:26-INFO: Version: 3.36.0
2023/09/19 09:59:26-INFO: config file is /home/rms/source/cmn_binviewer/config.ini
2023/09/19 10:02:06-CRITICAL: Traceback (most recent call last):
  File "/home/rms/source/cmn_binviewer/CMN_binViewer.py", line 3876, in __call__
    return self.func(*args)
  File "/home/rms/source/cmn_binviewer/CMN_binViewer.py", line 3766, in <lambda>
    save_as_jpg = StyledButton(self.save_panel, text="JPG", width = 5, command = lambda: self.save_image(extension = 'jpg', save_as = True))
  File "/home/rms/source/cmn_binviewer/CMN_binViewer.py", line 2328, in save_image
    shwr, mag = self.get_assoc_and_mag(timestamp = self.current_img_timestamp)
  File "/home/rms/source/cmn_binviewer/CMN_binViewer.py", line 2170, in get_assoc_and_mag
    dtval = datetime.datetime.strptime(timestamp.strip(), '%Y-%m-%d %H:%M:%S.%f')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains:  0149

149 is the number of the frame I was trying to save. "Embed name" was 
not selected. Using the "Save frames" option instead seems to work...

**Comment by markmac99** [comment]
Think this is an easy fix - at line 2170 we are converting the date stamp as a string into a datetime, but when in Detection mode, the datestamp has the frame number post-pended eg 2023-09-09 23:43:12.123 0123
So we just need to cut off only the first 24 chars
timestamp = timestamp[:24] # issue 68, crash when saving single frame

**Comment by markmac99** [comment]
fixed and tested. Release in version 3.36.1
